\set ON_ERROR_STOP on
\getenv rf_migrator_password RUTA_FIJA_MIGRATOR_PASSWORD
\getenv rf_app_password RUTA_FIJA_APP_PASSWORD
\getenv rf_test_password RUTA_FIJA_TEST_PASSWORD

BEGIN;
SET LOCAL password_encryption = 'scram-sha-256';

CREATE ROLE rf_migrator
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS
    PASSWORD :'rf_migrator_password';

CREATE ROLE rf_app
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS
    PASSWORD :'rf_app_password';

CREATE ROLE rf_test
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS
    PASSWORD :'rf_test_password';

COMMIT;
