package pe.rutafija.shared.exception;

public enum ErrorCode {
    AUTH_INVALID_CREDENTIALS,
    AUTH_TOKEN_INVALID,
    AUTH_TOKEN_EXPIRED,
    AUTH_REFRESH_REUSE_DETECTED,
    RATE_LIMIT_EXCEEDED,
    CROSS_ORIGIN_REQUEST_DENIED,
    FORBIDDEN_ROLE,
    TENANT_ACCESS_DENIED,
    DRIVER_NOT_ELIGIBLE,
    VEHICLE_NOT_ELIGIBLE,
    ASSIGNMENT_INVALID_TRANSITION,
    ASSIGNMENT_SCHEDULE_CONFLICT,
    INCIDENT_INVALID_STATE,
    REPORT_RANGE_REQUIRED,
    REPORT_RESULT_LIMIT_EXCEEDED,
    RESOURCE_VERSION_CONFLICT,
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    METHOD_NOT_ALLOWED,
    MEDIA_TYPE_NOT_SUPPORTED,
    RESOURCE_NOT_FOUND,
    RESOURCE_CONFLICT,
    INTERNAL_ERROR
}
